// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/command/command.go

// Package command_mock is a generated GoMock package.
package command_mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/ilya372317/pass-keeper/internal/client/domain"
)

// MockpassKeeperService is a mock of passKeeperService interface.
type MockpassKeeperService struct {
	ctrl     *gomock.Controller
	recorder *MockpassKeeperServiceMockRecorder
}

// MockpassKeeperServiceMockRecorder is the mock recorder for MockpassKeeperService.
type MockpassKeeperServiceMockRecorder struct {
	mock *MockpassKeeperService
}

// NewMockpassKeeperService creates a new mock instance.
func NewMockpassKeeperService(ctrl *gomock.Controller) *MockpassKeeperService {
	mock := &MockpassKeeperService{ctrl: ctrl}
	mock.recorder = &MockpassKeeperServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpassKeeperService) EXPECT() *MockpassKeeperServiceMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockpassKeeperService) All(arg0 context.Context) ([]domain.ShortData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", arg0)
	ret0, _ := ret[0].([]domain.ShortData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockpassKeeperServiceMockRecorder) All(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockpassKeeperService)(nil).All), arg0)
}

// Delete mocks base method.
func (m *MockpassKeeperService) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockpassKeeperServiceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockpassKeeperService)(nil).Delete), arg0, arg1)
}

// Login mocks base method.
func (m *MockpassKeeperService) Login(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockpassKeeperServiceMockRecorder) Login(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockpassKeeperService)(nil).Login), arg0, arg1, arg2)
}

// Register mocks base method.
func (m *MockpassKeeperService) Register(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockpassKeeperServiceMockRecorder) Register(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockpassKeeperService)(nil).Register), arg0, arg1, arg2)
}

// SaveBinary mocks base method.
func (m *MockpassKeeperService) SaveBinary(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBinary", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBinary indicates an expected call of SaveBinary.
func (mr *MockpassKeeperServiceMockRecorder) SaveBinary(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBinary", reflect.TypeOf((*MockpassKeeperService)(nil).SaveBinary), arg0, arg1, arg2)
}

// SaveCard mocks base method.
func (m *MockpassKeeperService) SaveCard(arg0 context.Context, arg1, arg2, arg3, arg4 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCard", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCard indicates an expected call of SaveCard.
func (mr *MockpassKeeperServiceMockRecorder) SaveCard(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCard", reflect.TypeOf((*MockpassKeeperService)(nil).SaveCard), arg0, arg1, arg2, arg3, arg4)
}

// SaveLogin mocks base method.
func (m *MockpassKeeperService) SaveLogin(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveLogin", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveLogin indicates an expected call of SaveLogin.
func (mr *MockpassKeeperServiceMockRecorder) SaveLogin(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLogin", reflect.TypeOf((*MockpassKeeperService)(nil).SaveLogin), arg0, arg1, arg2, arg3)
}

// SaveText mocks base method.
func (m *MockpassKeeperService) SaveText(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveText", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveText indicates an expected call of SaveText.
func (mr *MockpassKeeperServiceMockRecorder) SaveText(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveText", reflect.TypeOf((*MockpassKeeperService)(nil).SaveText), arg0, arg1, arg2)
}

// Show mocks base method.
func (m *MockpassKeeperService) Show(arg0 context.Context, arg1, arg2 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Show", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Show indicates an expected call of Show.
func (mr *MockpassKeeperServiceMockRecorder) Show(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Show", reflect.TypeOf((*MockpassKeeperService)(nil).Show), arg0, arg1, arg2)
}

// MockterminalInterfaceApp is a mock of terminalInterfaceApp interface.
type MockterminalInterfaceApp struct {
	ctrl     *gomock.Controller
	recorder *MockterminalInterfaceAppMockRecorder
}

// MockterminalInterfaceAppMockRecorder is the mock recorder for MockterminalInterfaceApp.
type MockterminalInterfaceAppMockRecorder struct {
	mock *MockterminalInterfaceApp
}

// NewMockterminalInterfaceApp creates a new mock instance.
func NewMockterminalInterfaceApp(ctrl *gomock.Controller) *MockterminalInterfaceApp {
	mock := &MockterminalInterfaceApp{ctrl: ctrl}
	mock.recorder = &MockterminalInterfaceAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockterminalInterfaceApp) EXPECT() *MockterminalInterfaceAppMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockterminalInterfaceApp) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockterminalInterfaceAppMockRecorder) Run(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockterminalInterfaceApp)(nil).Run), ctx)
}
