// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/handler/grpc/v1/handler.go

// Package v1_mock is a generated GoMock package.
package v1_mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/ilya372317/pass-keeper/internal/server/domain"
	dto "github.com/ilya372317/pass-keeper/internal/server/dto"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthService) Login(arg0 context.Context, arg1 dto.LoginDTO) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceMockRecorder) Login(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthService)(nil).Login), arg0, arg1)
}

// Register mocks base method.
func (m *MockAuthService) Register(arg0 context.Context, arg1 dto.RegisterDTO) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0, arg1)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthServiceMockRecorder) Register(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthService)(nil).Register), arg0, arg1)
}

// MockdataService is a mock of dataService interface.
type MockdataService struct {
	ctrl     *gomock.Controller
	recorder *MockdataServiceMockRecorder
}

// MockdataServiceMockRecorder is the mock recorder for MockdataService.
type MockdataServiceMockRecorder struct {
	mock *MockdataService
}

// NewMockdataService creates a new mock instance.
func NewMockdataService(ctrl *gomock.Controller) *MockdataService {
	mock := &MockdataService{ctrl: ctrl}
	mock.recorder = &MockdataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdataService) EXPECT() *MockdataServiceMockRecorder {
	return m.recorder
}

// SaveSimpleData mocks base method.
func (m *MockdataService) SaveSimpleData(arg0 context.Context, arg1 dto.SaveSimpleDataDTO) (*domain.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSimpleData", arg0, arg1)
	ret0, _ := ret[0].(*domain.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveSimpleData indicates an expected call of SaveSimpleData.
func (mr *MockdataServiceMockRecorder) SaveSimpleData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSimpleData", reflect.TypeOf((*MockdataService)(nil).SaveSimpleData), arg0, arg1)
}
